org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.19
fabric_api_version=0.155.2+26.1.2
forge_config_api_port_version=26.1.4

mod_id=stardew_fishing
mod_name=Stardew Fishing
mod_version=3.7-fabric
mod_group=com.bonker.stardewfishing
archives_base_name=stardew_fishing-fabric-26.1.2
